# synthetic-package: false
# حدد اسم ملف القالب الخاص بك
template-arb-file: intl_en.arb
# حدد المجلد الذي توجد به كل ملفات ARB
arb_dir: lib/l10n
output_dir: lib/generated
# يمكنك أيضاً تغيير اسم فئة التوطين من AppLocalizations إلى S إذا كنت تفضل ذلك
# output-class: S
